#!/bin/bash
# Copy-Paste Commands to Fix SAC 401 Error
# Replace YOUR_CLIENT_ID and YOUR_CLIENT_SECRET with actual values

echo "================================================"
echo "FIX SAC 401 UNAUTHORIZED ERROR"
echo "================================================"
echo ""
echo "STEP 1: Set SAC OAuth Credentials"
echo "Replace YOUR_CLIENT_ID and YOUR_CLIENT_SECRET below:"
echo ""
echo "cf set-env ai-predictive-agent SAC_CLIENT_ID \"YOUR_CLIENT_ID\""
echo "cf set-env ai-predictive-agent SAC_CLIENT_SECRET \"YOUR_CLIENT_SECRET\""
echo ""
echo "STEP 2: Restart the app"
echo "cf restart ai-predictive-agent"
echo ""
echo "STEP 3: Verify it's working"
echo "cf logs ai-predictive-agent --recent | grep -E '(OAuth|401|ERROR)'"
echo ""
echo "================================================"
echo ""
echo "QUICK COPY-PASTE (update values first!):"
echo ""
echo "# Set credentials (REPLACE WITH REAL VALUES)"
echo "cf set-env ai-predictive-agent SAC_CLIENT_ID \"YOUR_CLIENT_ID\""
echo "cf set-env ai-predictive-agent SAC_CLIENT_SECRET \"YOUR_CLIENT_SECRET\""
echo ""
echo "# Restart"
echo "cf restart ai-predictive-agent"
echo ""
echo "# Check logs"
echo "cf logs ai-predictive-agent --recent"
echo ""
echo "================================================"
echo "If you don't have OAuth credentials yet:"
echo "1. Log into SAC: https://cvs-pharmacy-q.us10.hcs.cloud.sap"
echo "2. Go to: System → Administration → App Integration"
echo "3. Create new OAuth Client with Grant Type: Client Credentials"
echo "4. Add scopes: Planning, Data Import"
echo "5. Copy Client ID and Secret (shown only once!)"
echo "================================================"
